# .gitpod.yml
tasks:
  - name: Setup & Info
    init: |
      python -m venv .venv
      source .venv/bin/activate
      pip install -r requirements.txt
    command: |
      source .venv/bin/activate
      echo "Welcome to your MLOps environment!"
      echo "Docker is running. MLflow is ready to be launched with 'docker-compose up -d'"
      gp open README.md

ports:
  - port: 5000
    onOpen: open-preview
