services:
  minio:
    image: 'minio/minio:latest'
    container_name: minio_server
    ports:
      - "9000:9000"  # API 
      - "9001:9001"  # UI
    volumes:
      - ./minio_data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"

  mlflow_server:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: mlflow_server
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow_db:/mlflow_db
    environment:
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:////mlflow_db/mlflow.db
      --default-artifact-root s3://mlflow-artifacts
    depends_on:
      - minio